### ISSUE TITLE
CakePHP 3.3 - Fatal error: Uncaught PDOException

### ISSUE THREAD

**Issue by Perzonallica** [DaoAndCo/cakephp-logging#2]
Hello,

I just upgraded my app to 3.3 RC1 and I'm getting these PDO errors where I use your plugin:

> Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in ***/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:36 Stack trace: #0 
> 
> Warning (2): PDOStatement::bindValue() expects parameter 3 to be integer, object given [CORE/src/Database/Statement/PDOStatement.php, line 72]
> 
> Notice: Array to string conversion in ***/vendor/cakephp/cakephp/src/Database/Log/QueryLogger.php on line 80

This is how I use the plugin:
`$this->Log->info('logout', 'User logged out', [], ['ip' => true]);`

**Comment by ozee31** [comment]
OK, I will install version 3.3 and I will try to reproduce the bug

**Comment by ozee31** [comment]
It's a bug with Cakephp 3.3 rc1.
It's fixed here :  https://github.com/cakephp/cakephp/commit/85de77e0a3dcebb21f4a70c3dff996784df42941, but it's not released actually.
