### ISSUE TITLE
Initialize schema problem

### ISSUE THREAD

**Issue by Perzonallica** [DaoAndCo/cakephp-logging#3]
Hi!

In some cases when I try to log I get a warning message like this: 

> Declaration of Logging\Model\Table\LogsTable::_initializeSchema(Cake\Database\Schema\Table $schema) should be compatible with Cake\ORM\Table::_initializeSchema(Cake\Database\Schema\TableSchema $schema) [ROOT/vendor/daoandco/cakephp-logging/src/Model/Table/LogsTable.php, line 0]

I didn't find out why I don't get this warning in the same controller, but in different action. 

I changed one line in this file:
`..\daoandco\cakephp-logging\src\Model\Table\LogsTable.php`

from `use Cake\Database\Schema\Table as Schema;` to `use Cake\Database\Schema\TableSchema as Schema;`

and now it seems to be working without any warning messages.

**Comment by ozee31** [comment]
Sorry, this project is no longer maintained
