### ISSUE TITLE
Method's depreceated in cakephp

### ISSUE THREAD

**Issue by IvanovAlmeida** [DaoAndCo/cakephp-logging#4]
I am getting one the following deprecation error in CakePHP 3.6.1. I changed the direct in the file, but, not interesting.

```
Deprecated (16384): Logging\Log\Engine\DatabaseLog::config() is deprecated. Use setConfig()/getConfig() instead. -
```

And ``` TableRegistry ``` will also be deprecated.

https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html#deprecations

**Comment by ozee31** [comment]
Sorry, this project is no longer maintained
